image:
  file: .gitpod.Dockerfile

tasks:
  - name: 'Setup and start DB'
    init: |
      git config --global pull.rebase false
      cd api && npm ci
      cd ../app && npm ci
      cd ..
      echo ""
      echo "Public API URL:"
      gp url 3000
      echo ""
      echo "Public App URL:"
      gp url 4200
      gp sync-done initial
      docker compose up

  - name: 'Start Api'
    init: |
      gp sync-await initial
      cd api && npm start

  - name: 'Start App'
    init: |
      gp sync-await initial
      cd app && npm start

ports:
  - port: 3000
    visibility: public

  - port: 4200
    visibility: public
    onOpen: open-browser
